// render.js — Pre-render localized pages for SEO + AI crawlers.
//
// Reads each .html file and applies i18n translations directly via the
// i18n module (loaded as a Node.js ES module). Then adds SEO headers
// (hreflang, OG tags, JSON-LD, canonical). Outputs fully-translated HTML
// into build/{locale}/ for GitHub Pages.
//
// Usage:  node scripts/render.js
//
// Output directory:  build/
//   build/index.html          (German, canonical root — no JS redirect)
//   build/de/index.html       (German duplicate for /de/ path)
//   build/de/fine-tune.html
//   build/de/uhpc.html
//   build/en/index.html
//   build/en/fine-tune.html
//   build/en/uhpc.html
//   build/css/, build/js/, build/locales/, build/assets/  (copied from repo root)
//   build/sitemap.xml, build/robots.txt                   (generated by sitemap.js)

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, statSync, rmSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { i18n } from '../js/lib/i18n-node.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const PAGES = ['index.html', 'fine-tune.html', 'uhpc.html'];
const LOCALES = ['de', 'en'];
const BUILD = join(ROOT, 'build');

// ── Apply i18n translations to HTML ─────────────────────────────────────
// Processes six attribute patterns (all on the same tag):
//
//   1. data-i18n="key"              → replace element text content
//   2. data-i18n-placeholder="key"  → replace placeholder="..."
//   3. data-i18n-meta="key"         → replace content="..." on <meta>
//   4. data-i18n-alt="key"          → replace alt="..." on <img>
//   5. data-i18n-titlepage="key"    → replace <title> text
//   6. data-i18n-as-html="true"     → on #1, treat result as raw HTML
//
// After translation, replaces {base} placeholders in all output with the
// given basePath (e.g. 'de/' for root index, '' for /de/ pages).

function translatePage(html, locale, basePath = '') {
  // 1 & 6. data-i18n on inline elements (most are same-line)
  html = html.replace(
    /(<[^>]*data-i18n="([^"]+)"[^>]*>)([\s\S]*?)(<\/[^>]+>)/gi,
    (_match, open, key, _inner, close) => {
      let text = i18n.t(key);
      if (basePath) text = text.replace(/\{base\}/g, basePath);
      return open + text + close;
    },
  );

  // 3. data-i18n-placeholder — replace placeholder="..." (any attr order)
  html = html.replace(
    /<(?!meta|title)[^>]*data-i18n-placeholder="([^"]+)"[^>]*>/gi,
    (tag) => {
      if (!tag.includes('placeholder=')) return tag;
      const key = tag.match(/data-i18n-placeholder="([^"]+)"/)[1];
      let val = i18n.t(key);
      if (basePath) val = val.replace(/\{base\}/g, basePath);
      return tag.replace(/placeholder="[^"]*"/, `placeholder="${val}"`);
    },
  );

  // 4. data-i18n-meta — replace content="..." on <meta> (any attr order)
  html = html.replace(
    /<meta[^>]*data-i18n-meta="([^"]+)"[^>]*>/gi,
    (tag) => {
      if (!tag.includes('content=')) return tag;
      const key = tag.match(/data-i18n-meta="([^"]+)"/)[1];
      let val = i18n.t(key);
      if (basePath) val = val.replace(/\{base\}/g, basePath);
      return tag.replace(/content="[^"]*"/, `content="${val}"`);
    },
  );

  // 5. data-i18n-alt — replace alt="..." on <img> (any attr order)
  html = html.replace(
    /<img[^>]*data-i18n-alt="([^"]+)"[^>]*>/gi,
    (tag) => {
      if (!tag.includes('alt=')) return tag;
      const key = tag.match(/data-i18n-alt="([^"]+)"/)[1];
      let val = i18n.t(key);
      if (basePath) val = val.replace(/\{base\}/g, basePath);
      return tag.replace(/alt="[^"]*"/, `alt="${val}"`);
    },
  );

  // 2. data-i18n-titlepage — replace <title> text, strip the data attr
  html = html.replace(
    /<title[^>]*data-i18n-titlepage="([^"]+)"[^>]*>[\s\S]*?<\/title>/gi,
    (_match, key) => {
      let text = i18n.t(key);
      if (basePath) text = text.replace(/\{base\}/g, basePath);
      return `<title>${text}</title>`;
    },
  );

  return html;
}

// ── SEO tag injection ───────────────────────────────────────────────────

function addSeoTags(html, locale, pageFile) {
  const pagePath = pageFile === 'index.html' ? '' : pageFile;
  const other = locale === 'de' ? 'en' : 'de';
  const ogLocale = locale === 'de' ? 'de_DE' : 'en_US';
  const baseUrl = 'https://chrip.github.io/CreteLab';

  const seoTags = [
    `<link rel="alternate" hreflang="${other}" href="${baseUrl}/${other}${pagePath ? '/' + pagePath : ''}">`,
    `<meta property="og:locale" content="${ogLocale}">`,
    `<link rel="canonical" href="${baseUrl}/${locale}${pagePath ? '/' + pagePath : ''}">`,
    `<script type="application/ld+json">\n${structuredData(locale, pageFile)}\n</script>`,
  ];

  return html.replace('</head>', seoTags.join('\n') + '\n  </head>');
}

// ── SEO tag injection for root index (canonical = root URL) ─────────────

function addSeoTagsRootIndex(html) {
  const baseUrl = 'https://chrip.github.io/CreteLab';
  const seoTags = [
    '<link rel="alternate" hreflang="en" href="' + baseUrl + '/en/">',
    '<meta property="og:locale" content="de_DE">',
    '<link rel="canonical" href="' + baseUrl + '/">',
    '<script type="application/ld+json">\n' + structuredData('de', 'index.html') + '\n</script>',
  ];
  return html.replace('</head>', seoTags.join('\n') + '\n  </head>');
}

// ── JSON-LD structured data ────────────────────────────────────────────

function structuredData(locale, page) {
  const descriptions = {
    'de': {
      'index.html': 'Professioneller Betonrechner basierend auf dem Zement-Merkblatt B 20.',
      'fine-tune.html': 'Zusatzstoffe für Ihr Betonrezept optimieren: Flugasche, Betonverflüssiger, Silikastaub oder Luftporenbildner.',
      'uhpc.html': 'Skalieren Sie veröffentlichte UHPC-Rezepte auf Ihr Volumen.',
    },
    'en': {
      'index.html': 'Professional concrete recipe calculator based on Zement-Merkblatt B 20.',
      'fine-tune.html': 'Additives for your concrete recipe: fly ash, plasticizer, silica fume or air-entraining agent.',
      'uhpc.html': 'Scale published UHPC recipes to your volume.',
    },
  };

  const pagePath = page === 'index.html' ? '' : page;
  const pageUrl = page === 'index.html'
    ? 'https://chrip.github.io/CreteLab/'
    : `https://chrip.github.io/CreteLab/${locale}/${page}`;

  const names = {
    de: {
      'index.html': 'CreteLab - Intelligenter Betonrezept Rechner',
      'fine-tune.html': 'CreteLab – Rezept feintunen',
      'uhpc.html': 'CreteLab – Hochleistungsbeton (UHPC)',
    },
    en: {
      'index.html': 'CreteLab - Intelligent Concrete Recipe Calculator',
      'fine-tune.html': 'CreteLab – Fine-Tune Your Recipe',
      'uhpc.html': 'CreteLab – Ultra-High Performance Concrete (UHPC)',
    },
  };

  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "WebApplication",
    "name": names[locale][page] || 'CreteLab',
    "description": descriptions[locale][page] || '',
    "url": pageUrl,
    "applicationCategory": "EngineeringApplication",
    "operatingSystem": "Web Browser",
    "browserRequirements": "Requires JavaScript",
    "inLanguage": ["de", "en"]
  }, null, 2);
}

// ── Copy static assets ──────────────────────────────────────────────────

function copyStaticAssets() {
  for (const name of ['css', 'js', 'locales', 'assets']) {
    const src = join(ROOT, name);
    const dest = join(BUILD, name);
    syncCopy(src, dest);
  }
}

function syncCopy(src, dest) {
  try {
    const stat = statSync(src);
    if (stat.isDirectory()) {
      mkdirSync(dest, { recursive: true });
      for (const entry of readdirSync(src)) {
        syncCopy(join(src, entry), join(dest, entry));
      }
    } else {
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, readFileSync(src));
    }
  } catch {
    // Skip files that don't exist or have restricted access
  }
}

// ── Main ────────────────────────────────────────────────────────────────────────

async function main() {
  if (existsSync(BUILD)) rmSync(BUILD, { recursive: true });
  mkdirSync(BUILD, { recursive: true });

  for (const locale of LOCALES) {
    await i18n.setLocale(locale, { force: true });
    const dir = join(BUILD, locale);
    mkdirSync(dir, { recursive: true });

    for (const page of PAGES) {
      console.log(`  ${locale}/${page}`);
      let html = readFileSync(join(ROOT, page), 'utf8');
      html = translatePage(html, locale, '');
      html = addSeoTags(html, locale, page);
      html = html.replace(/<html[^>]*lang="[^"]*"/, `<html lang="${locale}"`);

      // Assets live at build/css/, build/js/, etc. — locale pages in build/en/ need ../
      html = html.replace(
        /(src|href)="(css|js|assets|locales)\//g,
        '$1="../$2/',
      );
      html = html.replace(
        /import ['"]\.\/(js\/lib|js\/)/g,
        "import '../$1",
      );

      writeFileSync(join(dir, page), html, 'utf8');
    }
  }

  // Root index.html → actual German page (no JS redirect)
  // Canonical points to root URL; alternate hreflang to /en/
  {
    await i18n.setLocale('de', { force: true });
    let html = readFileSync(join(ROOT, 'index.html'), 'utf8');
    html = translatePage(html, 'de', 'de/');
    html = addSeoTagsRootIndex(html);
    html = html.replace(/<html[^>]*lang="[^"]*"/, `<html lang="de"`);

    // Root pages keep ./js/... as-is (already correct for build/ root)
    html = html.replace(
      /(src|href)="(css|js|assets|locales)\//g,
      '$1="$2/',
    );
    // Prefix page links with basePath (e.g. 'de/fine-tune.html') but not assets
    html = html.replace(/href="([^"]*)"/g, (_m, href) => {
      if (href.startsWith('http') || href.startsWith('#') || href.startsWith('mailto:')) return `href="${href}"`;
      if (/^(css|js|assets|locales)\//.test(href)) return `href="${href}"`;
      return `href="${'de/'}${href}"`;
    });

    writeFileSync(join(BUILD, 'index.html'), html, 'utf8');
  }

  copyStaticAssets();
  console.log('Static assets copied.');
  console.log(`Done. Output: ${BUILD}/`);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
